# setwd("C:\\Coursera\\Data Specialization Track\\Repositories\\ExData_Plotting1")
# install.packages("downloader")
# install.packages("tools")
# library(downloader)
# library (tools)
# fileUrl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
# download.file(fileUrl,"project1.zip")
# filename <- unzip("project1.zip")
# install.packages("sqldf")
# require("sqldf")
# mySql <- "Select * from file WHERE Date = '1/2/2007' OR Date = '2/2/2007'"
# myData <- read.csv.sql(filename,mySql,sep=";")
# dateFr <- paste(myData$Date,myData$Time)
# dateFr <- as.data.frame(dateFr, stringasFactors=FALSE)
# colnames(dateFr) <- "Date_Time"
# newdateFr <- strptime(dateFr$Date_Time,format="%d/%m/%Y %H:%M:%S")
# finalData <- cbind(newdateFr, myData[3:9])
# png("plot4.png",width=480,height=480)
setwd("C:\\Coursera\\Data Specialization Track\\Repositories\\ExData_Plotting1")
fileUrl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(fileUrl,"project1.zip")
filename <- unzip("project1.zip")
install.packages("sqldf")
library(sqldf)
mySql <- "Select * from file WHERE Date = '1/2/2007' OR Date = '2/2/2007'"
myData <- read.csv.sql(filename,mySql,sep=";")
dateFr <- as.data.frame(paste(myData$Date,myData$Time), stringasFactors=FALSE)
newdateFr <- strptime(dateFr[,1],format="%d/%m/%Y %H:%M:%S")
finalData <- cbind(newdateFr, myData[3:9])
par(mfrow = c(2, 2))
plot(finalData[,1],finalData[,2],typ="l",main="",xlab="datetime",ylab="Global active power")
plot(finalData[,1],finalData[,4],typ="l",main="",xlab="datetime",ylab="Voltage")
plot(finalData[,1],finalData[,6],col="black",typ="l", main="",xlab="",ylab="Energy sub metering")
lines(finalData[,1],finalData[,7],col="red",typ="l")
lines(finalData[,1],finalData[,8],col="blue",typ="l")
legend("topright", lty=1, col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
plot(finalData[,1],finalData[,3],typ="l",main="",xlab="datetime",ylab="Global_reactive_power")
dev.off()